# Generated by Django 2.2.5 on 2021-07-13 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='favourite_book_genre',
            field=models.CharField(choices=[('fantasy', 'Fantasy'), ('mystery', 'Mystery'), ('thriller', 'Thriller')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='favourite_movie_genre',
            field=models.CharField(choices=[('action', 'Action'), ('comedy', 'Comedy'), ('horror', 'Horror')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='language',
            field=models.CharField(choices=[('kr', 'Korean'), ('en', 'English')], default='kr', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='preference',
            field=models.CharField(choices=[('book', 'Book'), ('movie', 'Movie')], default='book', max_length=10, null=True),
        ),
    ]
