# Generated by Django 2.2.5 on 2021-07-13 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210713_1451'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='favourite_book_genre',
        ),
        migrations.RemoveField(
            model_name='user',
            name='favourite_movie_genre',
        ),
        migrations.AddField(
            model_name='user',
            name='favorite_book_genre',
            field=models.CharField(blank=True, choices=[('fantasy', 'Fantasy'), ('mystery', 'Mystery'), ('thriller', 'Thriller')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='favorite_movie_genre',
            field=models.CharField(blank=True, choices=[('action', 'Action'), ('comedy', 'Comedy'), ('horror', 'Horror')], max_length=20, null=True),
        ),
    ]
