# Generated by Django 2.2.5 on 2021-07-19 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20210715_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='language',
            field=models.CharField(choices=[('kr', 'Korean'), ('en', 'English')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='preference',
            field=models.CharField(choices=[('book', 'Book'), ('movie', 'Movie')], max_length=10, null=True),
        ),
    ]
