# Generated by Django 2.2.5 on 2021-07-19 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0002_auto_20210715_1158'),
        ('movies', '0002_auto_20210719_0713'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='cast',
        ),
        migrations.AddField(
            model_name='movie',
            name='cast',
            field=models.ManyToManyField(related_name='cast', to='people.Person'),
        ),
    ]
